name: Code Review 

on:
  push:
    branches: ["main"]


jobs:
  code_review:
    runs-on: ubuntu-latest

    strategy: 
      matrix: 
        node-version: [18.x, 16.x, 14.x, 12.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install


      - name: Check Coding Standards
        #run: npm run lint  
        run: echo "Running Lint"

      - name: Analyze Code Quality
        #run: npm run analyze  
         run: echo "Analyzing code quailty"


      - name: Scan for Security Vulnerabilities
        #run: npm run security-scan  
        run: echo "Scanning Security Vulnerabilities"
